# Generated by Django 2.2 on 2019-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("concordia", "0025_auto_20190329_1705")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="year",
            field=models.CharField(blank=True, max_length=50),
        )
    ]
