extends: ../../../../.eslintrc.yaml
env:
    browser: true
    es6: true
parserOptions:
    sourceType: module
rules:
    'unicorn/prevent-abbreviations':
        - 'error'
        - whitelist:
              el: true
